// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:

/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcl8hlnk6ijWHZ_VYQUMasIpMZtJuj1eM',
    appId: '1:934637232256:web:2e75f0ef3a322ed0890665',
    messagingSenderId: '934637232256',
    projectId: 'bbambbam-a937f',
    authDomain: 'bbambbam-a937f.firebaseapp.com',
    storageBucket: 'bbambbam-a937f.appspot.com',
    measurementId: 'G-5L8R47S827',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgDT3vUIhMxdgvBvvwiUYW35NndBL8wxw',
    appId: '1:934637232256:android:e59a5a18782612e9890665',
    messagingSenderId: '934637232256',
    projectId: 'bbambbam-a937f',
    storageBucket: 'bbambbam-a937f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6mhPL3INVKzJznqcCQmsqCMlFLbBSztY',
    appId: '1:934637232256:ios:b61cf39f9bd61a30890665',
    messagingSenderId: '934637232256',
    projectId: 'bbambbam-a937f',
    storageBucket: 'bbambbam-a937f.appspot.com',
    iosBundleId: 'com.example.bbambbam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6mhPL3INVKzJznqcCQmsqCMlFLbBSztY',
    appId: '1:934637232256:ios:b61cf39f9bd61a30890665',
    messagingSenderId: '934637232256',
    projectId: 'bbambbam-a937f',
    storageBucket: 'bbambbam-a937f.appspot.com',
    iosBundleId: 'com.example.bbambbam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcl8hlnk6ijWHZ_VYQUMasIpMZtJuj1eM',
    appId: '1:934637232256:web:7ccceb994e38cbcf890665',
    messagingSenderId: '934637232256',
    projectId: 'bbambbam-a937f',
    authDomain: 'bbambbam-a937f.firebaseapp.com',
    storageBucket: 'bbambbam-a937f.appspot.com',
    measurementId: 'G-GTJ4TN41DY',
  );
}
